workflow:
  name: "RAQ Document Generation"
  description: "Enhanced binary-tree workflow with parallel analysis and smart context injection"
  
  # Default configuration for all teams (can be overridden per team)
  model: "gpt-4o-mini"
  temperature: 0.3
  max_messages: 50
  allow_repeated_speaker: false  # Force agent handoff - no repeated speakers
  max_selector_attempts: 3
  termination_keyword: "TERMINATE"
  
  teams:
    - id: "epic_discovery"
      template: "Epic_Discovery_Team.yaml"
      output_file: "epic_discovery"
      depends_on: null  # Root node - no dependencies
      input_files: []
      step_files: []     # No previous steps to summarize
      agent_result: null # No previous agent result

    - id: "document_assembly"
      template: "Document_Assembly_Team.yaml"
      output_file: "final_raq_document"
      depends_on: "epic_discovery"  # Parallel to Process_Analysis_Team
      input_files:
        - "epic_discovery.md"  # Needs the epic discovery output for aggregation
      step_files: []     # Doesn't need step summaries
      agent_result: null # Content is in the input file
      # Team-specific configuration overrides
      max_messages: 30   # Document assembly needs more messages

    - id: "epic_analysis"
      template: "Process_Analysis_Team.yaml"
      output_file: "epic_analysis"
      depends_on: "epic_discovery"  # Parallel analysis of epic discovery
      input_files: []
      step_files:
        - "epic_discovery.steps.md"  # Analysis team needs step summaries
      agent_result: null  # Not needed - result is in step summaries
      # Team-specific configuration overrides
      max_messages: 20   # Process analysis is more focused

    - id: "document_analysis"
      template: "Process_Analysis_Team.yaml"
      output_file: "final_raw_document_analysis"
      depends_on: "document_assembly"  # Sequential analysis of assembled document
      input_files: []
      step_files:
        - "final_raq_document.steps.md"  # Analysis team needs step summaries
      agent_result: null  # Not needed - result is in step summaries
      # Team-specific configuration overrides  
      max_messages: 20   # Process analysis is more focused
